export const categorySlugToName: Record<string, string> = {
  "music-store": "Music Store",
  "fast-food": "Fast Food",
  "school": "School",
  "hospital": "Hospital",
  "coaching-center": "Coaching Center",
  "library": "Library",
  "education-center": "Education Center",
  "clothing-store": "Clothing Store",
  "clothing-wholesaler": "Clothing Wholesaler",
  "restaurant": "Restaurant",
  "restaurants": "Restaurant",
  "indian-restaurant": "Indian Restaurant",
  "wedding-services": "Wedding Services",
  "car-dealer": "Car Dealer",
  "auto-repair": "Auto Repair",
  "printing-services": "Printing Services",
  "book-store": "Book Store",
  "jeweler": "Jeweler",
  "asian": "Asian",
  "home-goods-store": "Home Goods Store",
  "fitness-center": "Fitness Center",
  "electronics-store": "Electronics Store",
  "store": "Store",
  "lodging": "Lodging",
  "dairy-store": "Dairy Store",
  "bakery-and-cake-shop": "Bakery And Cake Shop",
  "shoe-store": "Shoe Store",
  "chauffeur-service": "Chauffeur Service",
  "computer-repair-service": "Computer Repair Service",
  "hypermarket": "Hypermarket",
  "hotel": "Hotel",
  "hotels": "Hotel",
  // ...add all other mappings as needed
}; 