
/**
 * Utility functions for Razorpay integration
 */

// Type for Razorpay payment response
export interface RazorpayResponse {
  razorpay_payment_id: string;
  razorpay_order_id?: string;
  razorpay_signature?: string;
  razorpay_subscription_id?: string;
}

// Type for Razorpay error response
export interface RazorpayError {
  code: string;
  description: string;
  source: string;
  step: string;
  reason: string;
  metadata: {
    payment_id?: string;
    order_id?: string;
  };
}

// Type for Razorpay payment options
export interface RazorpayOptions {
  key: string;
  amount: number;
  currency: string;
  name: string;
  description: string;
  image?: string;
  order_id?: string;
  prefill?: {
    name?: string;
    email?: string;
    contact?: string;
  };
  notes?: Record<string, string>;
  theme?: {
    color?: string;
  };
  handler?: (response: RazorpayResponse) => void;
  modal?: {
    escape?: boolean;
    backdropclose?: boolean;
    ondismiss?: () => void;
  };
  retry?: {
    enabled?: boolean;
    max_count?: number;
  };
  send_sms_hash?: boolean;
  remember_customer?: boolean;
  readonly?: {
    email?: boolean;
    contact?: boolean;
  };
}

// Define Razorpay window interface
declare global {
  interface Window {
    Razorpay: any;
  }
}

// Production Razorpay API key - use this directly
const RAZORPAY_KEY_ID = "rzp_live_8PGS0Ug3QeCb2I";

/**
 * Get the Razorpay key
 */
export const getRazorpayKey = (): string => {
  return RAZORPAY_KEY_ID; // Always use the production key
};

/**
 * Load the Razorpay script
 * @returns A promise that resolves when the script is loaded
 */
export const loadRazorpayScript = (): Promise<void> => {
  console.log("Starting to load Razorpay script");
  return new Promise((resolve, reject) => {
    // Check if script already exists
    const existingScript = document.getElementById('razorpay-checkout-js');
    
    if (existingScript) {
      console.log("Razorpay script already exists, using it");
      // Check if Razorpay is available in window
      if (typeof window !== 'undefined' && window.Razorpay) {
        console.log("Razorpay object is available in window");
        resolve();
      } else {
        // If script exists but Razorpay is not available, wait a bit
        console.log("Script exists but Razorpay object not available yet, waiting...");
        const checkRazorpay = () => {
          if (typeof window !== 'undefined' && window.Razorpay) {
            console.log("Razorpay object is now available");
            resolve();
          } else {
            console.log("Waiting for Razorpay to initialize...");
            setTimeout(checkRazorpay, 500);
          }
        };
        
        setTimeout(checkRazorpay, 500);
      }
      return;
    }
    
    // Create and append the script
    const script = document.createElement('script');
    script.id = 'razorpay-checkout-js';
    script.src = 'https://checkout.razorpay.com/v1/checkout.js';
    script.async = true;
    script.defer = true;
    
    script.onload = () => {
      console.log("Razorpay script loaded successfully");
      // Wait to ensure Razorpay object is initialized
      const checkRazorpay = () => {
        if (typeof window !== 'undefined' && window.Razorpay) {
          console.log("Razorpay object available after script load");
          resolve();
        } else {
          console.log("Waiting for Razorpay to initialize after script load...");
          setTimeout(checkRazorpay, 500);
        }
      };
      
      setTimeout(checkRazorpay, 500);
    };
    
    script.onerror = (error) => {
      console.error("Failed to load Razorpay script:", error);
      reject(new Error("Failed to load Razorpay SDK"));
    };
    
    document.body.appendChild(script);
  });
};

/**
 * Validates if Razorpay is available in the window object
 */
export const isRazorpayAvailable = (): boolean => {
  const available = typeof window !== 'undefined' && window.Razorpay !== undefined;
  console.log("Razorpay available in window:", available);
  return available;
};

/**
 * Generate a Razorpay compatible receipt ID
 * @returns A unique receipt ID
 */
export const generateReceiptId = (): string => {
  return `receipt_${Date.now()}`;
};

/**
 * Generate a simple unique string for order ID
 */
export const generateOrderId = (): string => {
  // Note: In production, order IDs should be generated by your server
  // This is a temporary client-side implementation
  const timestamp = Date.now();
  const random = Math.floor(Math.random() * 1000000).toString().padStart(6, '0');
  return `order_${timestamp}${random}`;
};

/**
 * Convert amount to paise (smallest currency unit for INR)
 * Ensures minimum payment is ₹1 (100 paise)
 */
export const convertToPaise = (amount: number): number => {
  // Ensure minimum amount is 1 rupee (100 paise)
  // Round to ensure we have whole number of paise
  const paise = Math.max(Math.round(amount * 100), 100);
  console.log(`Converting amount ${amount} to ${paise} paise`);
  return paise;
};

/**
 * Ensure all values in the notes object are strings
 * Razorpay requires all notes values to be strings
 */
export const formatNotesForRazorpay = (notes?: Record<string, any>): Record<string, string> => {
  if (!notes) return {};
  
  const formattedNotes: Record<string, string> = {};
  Object.entries(notes).forEach(([key, value]) => {
    // Convert all values to strings (important for numbers, booleans, etc.)
    formattedNotes[key] = String(value);
  });
  
  return formattedNotes;
};

/**
 * Create and open Razorpay checkout
 * @param options Razorpay payment options
 * @returns Razorpay instance
 */
export const createRazorpayCheckout = (options: RazorpayOptions): any => {
  if (!isRazorpayAvailable()) {
    throw new Error("Razorpay is not available. Please refresh the page.");
  }
  
  // Ensure the key is always the production key
  const apiKey = getRazorpayKey();
  
  // Ensure all numeric values in notes are converted to strings
  const notesWithStringValues = formatNotesForRazorpay(options.notes);
  
  // Format options correctly - only include fields that Razorpay actually expects
  const formattedOptions = {
    ...options,
    key: apiKey,
    notes: notesWithStringValues,
    // Ensure amount is a number (not a string)
    amount: typeof options.amount === 'string' ? parseInt(options.amount) : options.amount,
    // Add these settings for better error handling
    retry: {
      enabled: false // Disable automatic retries to avoid duplicate charges
    },
    // Add these to help with auto payments for subscriptions
    remember_customer: true,
    send_sms_hash: true,
    // Add this to prevent backdrop closing issues
    modal: {
      ...options.modal,
      backdropclose: false,
      escape: false
    }
  };
  
  console.log("Creating Razorpay checkout with options:", formattedOptions);
  
  try {
    // Create Razorpay instance
    const razorpay = new window.Razorpay(formattedOptions);
    
    // Add error handler
    razorpay.on('payment.error', function(error: any) {
      console.error("Payment error:", error);
    });
    
    return razorpay;
  } catch (error) {
    console.error("Error creating Razorpay instance:", error);
    throw new Error("Failed to initialize payment gateway. Please try again.");
  }
};

/**
 * Verify Razorpay payment 
 * In production, this would be done on the server side
 */
export const verifyRazorpayPayment = async (paymentData: RazorpayResponse): Promise<boolean> => {
  console.log("Verifying payment:", paymentData);
  
  // In a real implementation, this should call your backend API for verification
  // using a secure cryptographic signature check
  // For demo purposes, we're just returning true
  
  // Simulate API call delay
  await new Promise(resolve => setTimeout(resolve, 500));
  
  return true;
};
